export const mockProducts = [
  {
    id: '1',
    title: '@cryptoking',
    username: 'cryptoking',
    category: 'telegram',
    price: 2500,
    originalPrice: 3200,
    followers: 48200,
    description: 'Established crypto channel with highly engaged audience. 3+ years of history, clean account, never flagged.',
    tags: ['crypto', 'finance', 'premium'],
    badge: 'HOT',
    badgeColor: '#ef4444',
    verified: true,
    views: 9823,
    rating: 4.9,
    reviews: 127,
    createdAt: '2024-03-15',
    stats: {
      age: '3 years',
      engagementRate: '8.4%',
      avgViews: '12K',
      country: 'Global',
    },
    seller: {
      id: 's1',
      username: 'verified_seller',
      rating: 4.97,
      sales: 234,
    },
  },
  {
    id: '2',
    title: '@nftdrops_official',
    username: 'nftdrops_official',
    category: 'telegram',
    price: 1800,
    originalPrice: null,
    followers: 31500,
    description: 'NFT alpha channel with dedicated community. High-quality subscribers from US/EU.',
    tags: ['nft', 'web3', 'alpha'],
    badge: 'NEW',
    badgeColor: '#22c55e',
    verified: true,
    views: 5421,
    rating: 4.7,
    reviews: 43,
    createdAt: '2024-06-01',
    stats: {
      age: '2 years',
      engagementRate: '11.2%',
      avgViews: '8K',
      country: 'US/EU 70%',
    },
    seller: {
      id: 's2',
      username: 'topdeals99',
      rating: 4.85,
      sales: 89,
    },
  },
  {
    id: '3',
    title: '@aitools_daily',
    username: 'aitools_daily',
    category: 'telegram',
    price: 3400,
    originalPrice: 4000,
    followers: 75000,
    description: 'Premium AI tools newsletter with 75K subscribers. Monetization-ready, high open rates.',
    tags: ['ai', 'tools', 'tech'],
    badge: 'PREMIUM',
    badgeColor: '#f5c518',
    verified: true,
    views: 18234,
    rating: 5.0,
    reviews: 312,
    createdAt: '2024-01-10',
    stats: {
      age: '1.5 years',
      engagementRate: '15.8%',
      avgViews: '22K',
      country: 'Global',
    },
    seller: {
      id: 's3',
      username: 'elite_accounts',
      rating: 5.0,
      sales: 501,
    },
  },
  {
    id: '4',
    title: '@tradingalerts_pro',
    username: 'tradingalerts_pro',
    category: 'telegram',
    price: 950,
    originalPrice: null,
    followers: 12800,
    description: 'Trading signals channel. Active community, multiple revenue streams already set up.',
    tags: ['trading', 'signals', 'finance'],
    badge: null,
    badgeColor: null,
    verified: false,
    views: 3102,
    rating: 4.3,
    reviews: 21,
    createdAt: '2024-07-20',
    stats: {
      age: '8 months',
      engagementRate: '6.1%',
      avgViews: '3.5K',
      country: 'Asia 60%',
    },
    seller: {
      id: 's4',
      username: 'quick_sell',
      rating: 4.5,
      sales: 37,
    },
  },
  {
    id: '5',
    title: '@lifestyle_luxury',
    username: 'lifestyle_luxury',
    category: 'instagram',
    price: 4200,
    originalPrice: 5000,
    followers: 120000,
    description: 'Luxury lifestyle Instagram with 120K organic followers. Fashion & travel niche. Monetization active.',
    tags: ['luxury', 'lifestyle', 'fashion'],
    badge: 'TOP',
    badgeColor: '#a855f7',
    verified: true,
    views: 22100,
    rating: 4.8,
    reviews: 189,
    createdAt: '2024-02-05',
    stats: {
      age: '4 years',
      engagementRate: '4.2%',
      avgViews: '85K reach',
      country: 'US/UK 80%',
    },
    seller: {
      id: 's3',
      username: 'elite_accounts',
      rating: 5.0,
      sales: 501,
    },
  },
  {
    id: '6',
    title: '+1 (332) XXX-XXXX',
    username: null,
    category: 'phone',
    price: 750,
    originalPrice: null,
    followers: null,
    description: 'US virtual number, never used for Telegram. Works for verification. Instant delivery.',
    tags: ['usa', 'virtual', 'verification'],
    badge: 'INSTANT',
    badgeColor: '#3b82f6',
    verified: true,
    views: 8930,
    rating: 4.6,
    reviews: 78,
    createdAt: '2024-08-01',
    stats: {
      age: 'New',
      engagementRate: 'N/A',
      avgViews: 'N/A',
      country: 'United States',
    },
    seller: {
      id: 's5',
      username: 'numstore',
      rating: 4.7,
      sales: 1204,
    },
  },
  {
    id: '7',
    title: '@techreviews_yt',
    username: 'techreviews_yt',
    category: 'youtube',
    price: 6800,
    originalPrice: 8500,
    followers: 89000,
    description: '89K YouTube subscribers in tech review niche. Monetized channel, $1.2K/mo AdSense.',
    tags: ['youtube', 'tech', 'monetized'],
    badge: 'HOT',
    badgeColor: '#ef4444',
    verified: true,
    views: 31500,
    rating: 4.9,
    reviews: 94,
    createdAt: '2024-04-12',
    stats: {
      age: '3 years',
      engagementRate: '5.8%',
      avgViews: '45K',
      country: 'English',
    },
    seller: {
      id: 's3',
      username: 'elite_accounts',
      rating: 5.0,
      sales: 501,
    },
  },
  {
    id: '8',
    title: '@dance_universe',
    username: 'dance_universe',
    category: 'tiktok',
    price: 2100,
    originalPrice: null,
    followers: 340000,
    description: 'TikTok dance & entertainment account. 340K followers, viral content history.',
    tags: ['tiktok', 'dance', 'viral'],
    badge: 'VIRAL',
    badgeColor: '#ec4899',
    verified: true,
    views: 14200,
    rating: 4.5,
    reviews: 56,
    createdAt: '2024-05-18',
    stats: {
      age: '2.5 years',
      engagementRate: '7.3%',
      avgViews: '180K',
      country: 'Global',
    },
    seller: {
      id: 's6',
      username: 'socialmarket',
      rating: 4.65,
      sales: 178,
    },
  },
];

export const mockPurchaseHistory = [
  {
    id: 'p1',
    productId: '4',
    productTitle: '@tradingalerts_pro',
    price: 950,
    date: '2024-11-15',
    status: 'completed',
  },
  {
    id: 'p2',
    productId: '6',
    productTitle: '+1 (332) XXX-XXXX',
    price: 750,
    date: '2024-10-22',
    status: 'completed',
  },
];
